version: '3'
services:
  node-app:
    build: . # Dockerfile
    ports:
      - '4000:3000'
    environment:
      - PORT=3000
    depends_on:
      - mongo # mongoを先にupさせる

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yuki
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
